  - alias: Turn on the receiver when family room speakers are turned on
    id: "000001"
    trigger:
      platform: state
      entity_id: media_player.family_room_speakers
      to: 'on'
    action:
      service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "23544292"

  - alias: 'SMS when garage door is open'
    id: "000002"
    trigger:
      platform: state
      entity_id: cover.garage_door_opener
      to: 'open'
      for:
        minutes: 15
    action:
      - service: notify.twilio
        data:
          message: "The garage door is open!"
          target:
            - "+13015183303"
            - "+12404468426"
