- id: 'speakers001'
  alias: Turn on receiver with family room speakers
  trigger:
  - entity_id: media_player.family_room_speakers
    platform: state
    to: 'on'
  action:
  - data:
      activity: "Listen to Music"
    entity_id: remote.harmony_hub
    service: remote.turn_on

- id: 'speakers002'
  alias: Turn off receiver with family room speakers
  trigger:
    - entity_id: media.family_room_speakers
      platform: state
      to: 'off'
  condition:
    condition: template
    value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') == 'Listen to Music' }}"
  action:
    entity_id: remote.harmony_hub
    service: remote.turn_off

- id: 'speakers003'
  alias: Change speaker source via IFTTT
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: set_source
  action:
    service: media_player.select_source
    data_template:
      entity_id: '{{ trigger.event.data.entity }}'
      source: '{{ trigger.event.data.source | title | replace("Tv","TV") }}'

- id: 'speakers004'
  alias: Change source for all speakers via IFTTT
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: set_source_all
  action:
    - service: media_player.select_source
      data_template:
        entity_id: media_player.kitchen_speakers
        source: '{{ trigger.event.data.source | title | replace("Tv","TV") }}'
    - service: media_player.select_source
      data_template:
        entity_id: media_player.sunroom_speakers
        source: '{{ trigger.event.data.source | title | replace("Tv","TV") }}'
    - service: media_player.select_source
      data_template:
        entity_id: media_player.family_room_speakers
        source: '{{ trigger.event.data.source | title | replace("Tv","TV") }}'
    - service: media_player.select_source
      data_template:
        entity_id: media_player.playroom_speakers
        source: '{{ trigger.event.data.source | title | replace("Tv","TV") }}'
    - service: media_player.select_source
      data_template:
        entity_id: media_player.office_speakers
        source: '{{ trigger.event.data.source | title | replace("Tv","TV") }}'

- id: 'garage001'
  alias: SMS when garage door is open for 15 mins
  trigger:
  - entity_id: cover.garage_door_opener
    for: 0:15:00
    platform: state
    to: open
  action:
    service: script.turn_on
    entity_id: script.send_text_message
    data:
      variables:
          message: 'The garage door has been open for 15 minutes'

- id: 'garage002'
  alias: SMS when garage door is open for an hour
  trigger:
  - entity_id: cover.garage_door_opener
    for: 1:00:00
    platform: state
    to: open
  action:
    service: script.turn_on
    entity_id: script.send_text_message
    data:
      variables:
        message: 'The garage door has been open for an hour'

- id: 'garage003'
  alias: SMS when garage door is open at sunset
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: cover.garage_door_opener
    state: open
    for: 0:15:00
  action:
    service: script.turn_on
    entity_id: script.send_text_message
    data:
      variables:
        message: 'The sun has set and the garage door is open!'

- id: 'office001'
  alias: Turn on shelf lamps with desk lamp
  trigger:
  - entity_id: switch.office_desk_light
    platform: state
    to: "on"
  action:
    - service: switch.turn_on
      entity_id: group.office_shelf_lamps

- id: 'office002'
  alias: Turn off shelf lamps with desk lamp
  trigger:
  - entity_id: switch.office_desk_light
    platform: state
    to: "off"
  action:
    - service: switch.turn_off
      entity_id: group.office_shelf_lamps
      
