- platform: template
  switches:
    steam_link:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play on Steam Link') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Play on Steam Link'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    music:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Listen to Music') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Listen to Music'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    netflix:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Netflix') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch Netflix'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    tv:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch TV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    whole_home_tv:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play TV on Whole House') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Play TV on Whole House'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    office_chromecast:
      value_template: "{{ is_state_attr('media_player.office_speakers', 'source', 'Chromecast') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_speakers_on_set_source
        data:
          variables:
            speaker_zone: media_player.office_speakers
            source: 'Chromecast'
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.office_speakers
    office_office:
      value_template: "{{ is_state_attr('media_player.office_speakers', 'source', 'Office') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_speakers_on_set_source
        data:
          variables:
            speaker_zone: media_player.office_speakers
            source: 'Office'
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.office_speakers
    office_record_player:
      value_template: "{{ is_state_attr('media_player.office_speakers', 'source', 'Record Player') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_speakers_on_set_source
        data:
          variables:
            speaker_zone: media_player.office_speakers
            source: 'Record Player'
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.office_speakers
    office_tv:
      value_template: "{{ is_state_attr('media_player.office_speakers', 'source', 'TV') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_speakers_on_set_source
        data:
          variables:
            speaker_zone: media_player.office_speakers
            source: 'TV'
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.office_speakers
- platform: tplink
  host: !secret tplink_ip_office_lamp1
- platform: tplink
  host: !secret tplink_ip_office_lamp2
